---
abstract: 'interact with Gerrit code review tool'
author:
  - 'Rohan McGovern <rohan@mcgovern.id.au>'
build_requires:
  Dir::Self: 0
  Env::Path: 0
  File::chdir: 0
  LWP: 0
  List::MoreUtils: 0
  Sub::Override: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gerrit-Client
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Capture::Tiny: 0
  Data::Alias: 0
  File::chdir: 0
  JSON: 0
  Params::Validate: 0
  URI: 0
  perl: 5.01
version: 20121218
